spring.datasource.url=jdbc:postgresql://dpg-d6khrnlactks739tvp50-a/myappbackend
spring.datasource.username=myappbackend_user
spring.datasource.password=ds4IbjjYuvvADveNc8j9nIt5xKwZmql4
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8082}

app.faces.dir=data/faces
